# Generated by Django 5.0 on 2023-12-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_alter_pergunta_data_encerramento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='total_respostas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
