# Generated by Django 5.0 on 2023-12-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0004_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcaoresposta',
            name='quantidade_votada',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='total_respostas',
            field=models.IntegerField(default=0),
        ),
    ]
