# Generated by Django 5.0 on 2023-12-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0005_opcaoresposta_quantidade_votada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcaoresposta',
            name='quantidade_votada',
        ),
    ]
